export const BACKGROUND_ART_PROMPT: string = 'unpopulated, visual novel background scenery, background only, scenery only';

export const DEFAULT_BORDER_COLOR: string = '#999999dd';
export const DEFAULT_HIGHLIGHT_COLOR: string = '#ffffff';

export type Background = {
    // A unique identifier for the background
    id: string;
    // A name for the background
    name: string;
    // Description generated by the AI, used for generating the image
    artPrompt: string;
    // The background image URL
    backgroundUrl: string;
    // The depth map URL for the background
    depthUrl: string;
    // Border color associated with this background
    borderColor: string;
    // Highlight color associated with this background
    highlightColor: string;
    // Comma-delimited list of trigger words that will swap to this background
    triggerWords: string;
    // Whether this background is global (applies to all chats with the primary character)
    global: boolean;
}